# Generated by Django 5.2.7 on 2025-11-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
