# Generated by Django 5.2.7 on 2025-11-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_alter_quizresult_options_alter_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
