# Generated by Django 5.2.7 on 2025-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_alter_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
